# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "clap-0.11.0-oBajB-HnAQDPCKYzwF7rO3qDFwRcD39Q0DALlTSz5H7e";
    path = fetchzip {
      url = "https://github.com/Hejsil/zig-clap/archive/refs/tags/0.11.0.tar.gz";
      hash = "sha256-XytqwtoE0xaR43YustgK68sAQPVfC0Dt+uCs8UTfkbU=";
    };
  }
  {
    name = "zlob-1.2.9-zzE2lTSzBQCVffT9R1cuizDZuf7tCnw6mD4SGc2p5Trc";
    path = fetchgit {
      url = "https://github.com/dmtrKovalenko/zlob";
      rev = "5882d53d5d7e34cbe2465f0aaa45e2c902bee0df";
      hash = "sha256-52+g969K0DT5E2KxEEoLSsifW7PGOyu2IHyyrPlbFKI=";
    };
  }
]
